=== Firion711/Camponogarese/xml/calendarioPartite.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.camponogarese.it"
    targetNamespace="http://www.camponogarese.it"
    elementFormDefault="qualified">
	
	<xs:element name="calendarioPartite" type="TcalendarioPartite" />
	
	
	<xs:complexType name="TcalendarioPartite">
		<xs:sequence>
			<xs:element name="squadraDiCasa" type="Tsquadra" />
			<xs:element name="squadraInTrasferta" type="Tsquadra" />
			<xs:element name="dataPartita" type="Tdata" />
	<!--ho messo minOccurs=0 per dare all'admin la possibilità di "preparare l'evento" con il prossimo incontro,cioè intanto mettere la data e le squadre senza il risultato perchè l'incotro deve ancora disputarsi XD (da valutare se ha senso) -->
			<xs:element name="goalSquadCasa" type="Tgoal" minOccurs="0" maxOccurs="1"/>
			<xs:element name="goalSquadTrasf" type="Tgoal" minOccurs="0" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	


	<!-- Restrinzione per il nome delle squadre devono iniziare con una lettere maiuscola e poi una o più lettere minuscole; può essere composta da due parti -->
	<!-- !!!!!!!!!!!!!! NON SO SE ESISTANO SQUADRE CON IL NOME SPEZZATO !!!!!!!!!! QUINDI NN SO SE HA SENSO -->		
	<xs:simpleType name="Tsquadra" >
    	<xs:restriction base="xs:string">
    		<xs:pattern value="([A-Z][a-z]+( ([A-Z][a-z]+))?)" />
   		</xs:restriction>
   	</xs:simpleType>
	
	
	<!-- tipo data semplice con restrizione, stessa cosa come l'altro documento, scelta tra simpleType ristretto e complexType diviso da valutare -->
	<xs:simpleType name="Tdata">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-3]{1}[0-9]{1}/[0,1]{1}[0-9]{1}/[0-9]{4}" />
		</xs:restriction>
	</xs:simpleType>	
		
    
	<!-- Tipo complesso Tdata composto da giorno,mese e anno; non è stato usato il tipo xs:date perchè verrebbe visualizzato in formato italiano 
	<xs:complexType name="Tdata">
		<xs:sequence>
			<xs:element name="giorno" type="Tgiorno"/>		 
			<xs:element name="mese" type="Tmese"/>
			<xs:element name="anno" type="Tanno"/>				
		</xs:sequence>
	</xs:complexType>
	
	
	
	 il giorno può esser un valore tra 1 e 31 
	<xs:simpleType name="Tgiorno">
		<xs:restriction base="xs:positiveInteger">
			<xs:minInclusive value="1" />
			<xs:maxInclusive value="31" />
		</xs:restriction>
	</xs:simpleType>

	 il mese può assumere una enumerazione tra 01 e 12, con inclusi i due separatori / 
	<xs:simpleType name="Tmese">
		<xs:restriction base="xs:string">
				<xs:enumeration value="/01/" />
				<xs:enumeration value="/02/" />
				<xs:enumeration value="/03/" />
				<xs:enumeration value="/04/" />
				<xs:enumeration value="/05/" />
				<xs:enumeration value="/06/" />
				<xs:enumeration value="/07/" />
				<xs:enumeration value="/08/" />
				<xs:enumeration value="/09/" />
				<xs:enumeration value="/10/" />
				<xs:enumeration value="/11/" />
				<xs:enumeration value="/12/" />
		</xs:restriction>	
	</xs:simpleType>

	 l'anno	può essere un intero a 4 cifre compreso tra 1900 e 2016 
	<xs:simpleType name="Tanno">
		<xs:restriction base="xs:positiveInteger">
				<xs:minInclusive value="1900" />
				<xs:maxInclusive value="2016" />
		</xs:restriction>
	</xs:simpleType>
	-->
	
	<!-- Tipo che fefinisce il numero dei goal-->
	<xs:simpleType name="Tgoal">
		<xs:restriction base="xs:integer">
			<xs:pattern value="[0-9]{1,2}" /><!-- più di 99 goal è difficile farli in 90 minuti :P -->
		</xs:restriction>
	</xs:simpleType> 
		
</xs:schema>

=== Firion711/Camponogarese/xml/file calendario partite/calendarioPartite.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="calendarioPartite.xslt"?>
<calendarioPartite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.camponogarese.it"
	xsi:schemaLocation="http://www.camponogarese.it calendarioPartite.xsd">
	
	<!-- 4째 partita campionato -->
	<squadraDiCasa>Camponogarese</squadraDiCasa>
	<squadraInTrasferta>Thermal Teolo</squadraInTrasferta>
	<dataPartita>27/09/2015</dataPartita>
	<goalSquadCasa>3</goalSquadCasa>
	<goalSquadTrasf>0</goalSquadTrasf>

	<!-- 3째 partita campionato -->
	<squadraDiCasa>Camponogarese</squadraDiCasa>
	<squadraInTrasferta>Bussolengo</squadraInTrasferta>
	<dataPartita>20/09/2015</dataPartita>
	<goalSquadCasa>0</goalSquadCasa>
	<goalSquadTrasf>1</goalSquadTrasf>

	<!-- 2째 partita campionato -->
	<squadraDiCasa>Solesinese</squadraDiCasa>
	<squadraInTrasferta>Camponogarese</squadraInTrasferta>
	<dataPartita>13/09/2015</dataPartita>
	<goalSquadCasa>0</goalSquadCasa>
	<goalSquadTrasf>0</goalSquadTrasf>

	<!-- 1째 partita campionato -->
	<squadraDiCasa>Camponogarese</squadraDiCasa>
	<squadraInTrasferta>Clodiense</squadraInTrasferta>
	<dataPartita>06/09/2015</dataPartita>
	<goalSquadCasa>2</goalSquadCasa>
	<goalSquadTrasf>1</goalSquadTrasf>

</calendarioPartite>
