=== Firion711/Camponogarese/xml/organizzazione.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.camponogarese.it"
    targetNamespace="http://www.camponogarese.it"
    elementFormDefault="qualified">
	
	<xs:element name="organizzazione" type="Torganizzazione" />
	
	
	<xs:complexType name="Torganizzazione">
		<xs:sequence>
			<xs:element name="amministratori" type="Tamministratori" />
			<xs:element name="dipendenti" type="Tdipendenti" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- amministratori prima di manager per dare la possibilità di aggiungere altre figure all'interno dell'organizzazione -->
	<xs:complexType name="Tamministratori" >
		<xs:sequence>
			<xs:element name="manager" type="Tdati" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- si chiama Tdati perchè riuso il tipo anche per i dipendenti-->
	<xs:complexType name="Tdati" >
		<xs:sequence>
			<xs:element name="nome" type="xs:string" />
			<xs:element name="cognome" type="xs:string" />
			<xs:element name="dataNascita" type="xs:string" />
			<xs:element name="telefono" type="Ttelefono" />
		</xs:sequence>
	</xs:complexType>
	
	
	<!-- ok anche numeri di cellulare, ho evitato il 0039 iniziale -->
	<xs:simpleType name="Ttelefono">
		<xs:restriction base="xs:string">
			<xs:pattern value="0?[0..9]{2,3}-[0..9]+" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="Tdipendenti">
		<xs:sequence>
			<xs:element name="allenatori" type="Tdati" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== Firion711/Camponogarese/xml/organizzazione.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="organizzazione.xslt"?>
<organizzazione xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xmlns="http://www.camponogarese.it"
	xsi:schemaLocation="http://www.camponogarese.it organizzazione.xsd">
	
	<amministratori>
		<manager>
			<nome>Gilby</nome>
<<<<<<< HEAD
			<cognome>Gilby</cognome>
			<dataNascita>01/01/1111</dataNascita>
=======
			<cognome>Gilby Gilby</cognome>
			<dataNascita>32/12/1999</dataNascita>
>>>>>>> 9bfa4d0d38b0ea8c745072ba00106dbfc66738bd
			<telefono>000-0000000</telefono>
		</manager>
	</amministratori>
	<dipendenti>
		<allenatore>
			<nome>Gilby</nome>
			<cognome>Gilby</cognome>
<<<<<<< HEAD
			<dataNascita>01/01/1111</dataNascita>
=======
			<dataNascita>02/02/1990</dataNascita>
>>>>>>> 9bfa4d0d38b0ea8c745072ba00106dbfc66738bd
			<telefono>000-0000000</telefono>
		</allenatore>
	</dipendenti>
</organizzazione>

=== Firion711/Camponogarese/data/organizzazione.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="chisiamo.xsl"?>
<organizzazione xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.camponogarese.it" xsi:schemaLocation="http://www.camponogarese.it organizzazione.xsd">
	
	<amministratori>
		<manager>
			<nome>Nomeuno</nome>
			<cognome>Cognomeuno</cognome>
			<dataNascita>01/01/2000</dataNascita>
			<telefono>000-0000000</telefono>
		</manager>
		<manager>
			<nome>Nomedue</nome>
			<cognome>Cognomedue</cognome>
			<dataNascita>02/02/2000</dataNascita>
			<telefono>0000000000</telefono>
		</manager>
	
		<manager>
			<nome>Daniel</nome>
			<cognome>De Gaspari</cognome>
			<dataNascita>27-08-1994</dataNascita>
			<telefono>041414141</telefono>
		</manager>
	
		<manager>
			<nome>Daniel</nome>
			<cognome>De Gaspari</cognome>
			<dataNascita>27-08-1994</dataNascita>
			<telefono>041-414141</telefono>
		</manager>
	
		<manager>
			<nome>Riccardo</nome>
			<cognome>Mao</cognome>
			<dataNascita>27-08-1994</dataNascita>
			<telefono>041414141</telefono>
		</manager>
	
		<manager>
			<nome>Riccardo</nome>
			<cognome>Mao</cognome>
			<dataNascita>01/01/1994</dataNascita>
			<telefono>041-414141</telefono>
		</manager>
	
		<manager>
			<nome>Jordan</nome>
			<cognome>Gottardo</cognome>
			<dataNascita>27-08-1994</dataNascita>
			<telefono>041-414141</telefono>
		</manager>
	
		<manager>
			<nome>Jordan</nome>
			<cognome>Gottardo</cognome>
			<dataNascita>27-08-1994</dataNascita>
			<telefono>041414141</telefono>
		</manager>
	</amministratori>
	
	<dipendenti>
		<allenatori>
			<nome>Nometre</nome>
			<cognome>Cognometre</cognome>
			<dataNascita>02/02/2002</dataNascita>
			<telefono>000-0000000</telefono>
		</allenatori>
	
		<allenatori>
			<nome>Riccardo</nome>
			<cognome>Mao</cognome>
			<dataNascita>01/01/1994</dataNascita>
			<telefono>041-414141</telefono>
		</allenatori>
	
		<allenatori>
			<nome>Riccardo</nome>
			<cognome>Mao</cognome>
			<dataNascita>01/01/1994</dataNascita>
			<telefono>041-414141</telefono>
		</allenatori>
	
		<allenatori>
			<nome>Riccardo</nome>
			<cognome>Mao</cognome>
			<dataNascita>01/01/1994</dataNascita>
			<telefono>041-414141</telefono>
		</allenatori>
	</dipendenti>
</organizzazione>
<!-- Questo e' valido -->
